// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataAccess.Models;

public partial class HeaderE
{
    public int Id { get; set; }

    public decimal F1 { get; set; }

    public string F2 { get; set; }

    public string F3 { get; set; }

    public string F4 { get; set; }

    public string F5 { get; set; }

    public string F6 { get; set; }

    public string F7 { get; set; }

    public string F8 { get; set; }

    public string F9 { get; set; }

    public string F10 { get; set; }

    public string F11 { get; set; }

    public string F12 { get; set; }

    public string F13 { get; set; }

    public string F14 { get; set; }

    public string F15 { get; set; }

    public string F16 { get; set; }

    public string F17 { get; set; }

    public string F18 { get; set; }

    public string F19 { get; set; }

    public string F20 { get; set; }

    public string F21 { get; set; }

    public string F22 { get; set; }

    public string F23 { get; set; }

    public string F24 { get; set; }

    public string F25 { get; set; }

    public string F26 { get; set; }

    public string F27 { get; set; }

    public string F28 { get; set; }

    public string F29 { get; set; }

    public string F30 { get; set; }

    public string F31 { get; set; }

    public string F32 { get; set; }

    public string F33 { get; set; }

    public string F34 { get; set; }

    public string F35 { get; set; }

    public string F36 { get; set; }

    public string F37 { get; set; }

    public string F38 { get; set; }

    public decimal? Idplic { get; set; }
}