// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

namespace DataAccess.Models;

public interface IOpis
{
	double? Cantitate { get; set; }
	string CodZona1 { get; set; }
	string CodZona2 { get; set; }
	DateTime? Data { get; set; }
	string DeLa { get; set; }
	string DeLaF { get; set; }
	string Exp12 { get; set; }
	string Facturi { get; set; }
	string Judet { get; set; }
	string Masina { get; set; }
	int NumarCutie { get; set; }
	string NumeZona { get; set; }
	string Oras { get; set; }
	string OrasDestinatie { get; set; }
	string PanaLa { get; set; }
	string PanaLaF { get; set; }
	string PlicuriPelicula { get; set; }
	string SerieFact { get; set; }
	string SfStart { get; set; }
	string SfStop { get; set; }
	string Term { get; set; }
}