// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System.ComponentModel.DataAnnotations;

namespace DataAccess.Models;

public partial class Opis : IOpis
{
	[Key]
	public int NumarCutie { get; set; }

	public string Judet { get; set; }

	public string Oras { get; set; }

	public string CodZona1 { get; set; }

	public string CodZona2 { get; set; }

	public double? Cantitate { get; set; }

	public string DeLa { get; set; }

	public string PanaLa { get; set; }

	public string DeLaF { get; set; }

	public string PanaLaF { get; set; }

	public string SerieFact { get; set; }

	public string SfStart { get; set; }

	public string SfStop { get; set; }

	public string Exp12 { get; set; }

	public string Facturi { get; set; }

	public string NumeZona { get; set; }

	public string PlicuriPelicula { get; set; }

	public string OrasDestinatie { get; set; }

	public string Term { get; set; }

	public DateTime? Data { get; set; }

	public string Masina { get; set; }
}