// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;

namespace DataAccess.Models;

public partial class RDSContext : DbContext
{
	public RDSContext( DbContextOptions<RDSContext> options )
		 : base(options)
	{
	}

	public virtual DbSet<HeaderE> HeaderE { get; set; }

	public virtual DbSet<Opis> Opis { get; set; }

	protected override void OnModelCreating( ModelBuilder modelBuilder )
	{
		modelBuilder.Entity<HeaderE>(entity =>
		{
			entity.Property(e => e.Id)
					.ValueGeneratedNever()
					.HasColumnName("ID");
			entity.Property(e => e.F1).HasColumnType("decimal(18, 0)");
			entity.Property(e => e.Idplic)
					.HasColumnType("decimal(18, 0)")
					.HasColumnName("IDPLIC");
		});

		modelBuilder.Entity<Opis>(entity =>
		{
			entity.ToTable("opis");

			entity.Property(e => e.Cantitate).HasColumnName("cantitate");
			entity.Property(e => e.CodZona1)
					.HasMaxLength(255)
					.HasColumnName("cod_zona_1");
			entity.Property(e => e.CodZona2)
					.HasMaxLength(255)
					.HasColumnName("cod_zona_2");
			entity.Property(e => e.Data).HasColumnType("smalldatetime");
			entity.Property(e => e.DeLa)
					.HasMaxLength(255)
					.HasColumnName("de_la");
			entity.Property(e => e.DeLaF)
					.HasMaxLength(255)
					.HasColumnName("de_laF");
			entity.Property(e => e.Exp12)
					.HasMaxLength(255)
					.HasColumnName("exp_12");
			entity.Property(e => e.Facturi)
					.HasMaxLength(50)
					.HasColumnName("facturi");
			entity.Property(e => e.Judet)
					.HasMaxLength(255)
					.HasColumnName("judet");
			entity.Property(e => e.Masina)
					.HasMaxLength(10)
					.IsFixedLength()
					.HasColumnName("masina");
			entity.Property(e => e.NumarCutie).HasColumnName("numar_cutie");
			entity.Property(e => e.NumeZona)
					.HasMaxLength(255)
					.HasColumnName("nume_zona");
			entity.Property(e => e.Oras)
					.HasMaxLength(255)
					.HasColumnName("oras");
			entity.Property(e => e.OrasDestinatie)
					.HasMaxLength(255)
					.HasColumnName("oras_destinatie");
			entity.Property(e => e.PanaLa)
					.HasMaxLength(255)
					.HasColumnName("pana_la");
			entity.Property(e => e.PanaLaF)
					.HasMaxLength(255)
					.HasColumnName("pana_laF");
			entity.Property(e => e.PlicuriPelicula)
					.HasMaxLength(255)
					.HasColumnName("plicuri_pelicula");
			entity.Property(e => e.SerieFact)
					.HasMaxLength(255)
					.HasColumnName("serie_fact");
			entity.Property(e => e.SfStart)
					.HasMaxLength(255)
					.HasColumnName("sf_start");
			entity.Property(e => e.SfStop)
					.HasMaxLength(255)
					.HasColumnName("sf_stop");
			entity.Property(e => e.Term)
					.HasMaxLength(5)
					.HasColumnName("term");
		});

		OnModelCreatingPartial(modelBuilder);
	}

	partial void OnModelCreatingPartial( ModelBuilder modelBuilder );
}